{"name": "Ошибка при попытке повторного создания существующего пользователя", "status": "passed", "start": 1714680865668, "stop": 1714680866028, "uuid": "3b46ba3d-3693-4e9c-95d2-b64df45cf507", "historyId": "ee624a903a128a87a0e335d787c8bd5c", "testCaseId": "ee624a903a128a87a0e335d787c8bd5c", "fullName": "tests.test_user_creating.TestUserCreating#test_register_double_user_failed_result", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_creating"}, {"name": "subSuite", "value": "TestUserCreating"}, {"name": "host", "value": "DESKTOP-6OEUNT0"}, {"name": "thread", "value": "4572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_creating"}]}