{"name": "Ошибка при проверке пользователя с некорректным логином", "status": "passed", "start": 1714680874700, "stop": 1714680875040, "uuid": "f120ad4f-ea9f-42de-800f-b8a9d552dd79", "historyId": "021d1382136918c937b9ab332420afe2", "testCaseId": "021d1382136918c937b9ab332420afe2", "fullName": "tests.test_user_login.TestUserLogin#test_login_incorrect_email_failed_result", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "DESKTOP-6OEUNT0"}, {"name": "thread", "value": "4572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}