{"name": "Ошибка проверки получения заказов неавторизованного пользователя", "status": "passed", "start": 1714680880202, "stop": 1714680880568, "uuid": "6e781b61-6818-4631-9fb3-508234b8cb0e", "historyId": "53bd97dd91d96d0445b08e950f86efb7", "testCaseId": "53bd97dd91d96d0445b08e950f86efb7", "fullName": "tests.test_user_order_getting.TestUserOrderGetting#test_getting_order_unauthorized_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_order_getting"}, {"name": "subSuite", "value": "TestUserOrderGetting"}, {"name": "host", "value": "DESKTOP-6OEUNT0"}, {"name": "thread", "value": "4572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_order_getting"}]}
